# Generated by Django 4.0.4 on 2022-11-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapiconfig',
            name='secret_key',
        ),
    ]
