# Generated by Django 4.0.4 on 2022-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userapiconfig_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapiconfig',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
